### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) :    SystemExit: None 

### ISSUE THREAD

**Issue by brickyyyy** [bioFAM/MOFA#23] opened 2019-01-17 12:06 UTC
I get this error after running the following
`#run MOFA
MOFAobject = runMOFA(MOFAobject)
`
If you have any guesses of where it might stem from, I will be happy to hear.

**Comment by rargelaguet** [comment] 2019-01-17 12:07
I was actually fixing it right now. Can you pull the last commit and try again?

**Comment by brickyyyy** [comment] 2019-01-17 12:12
The issue still occurs even after updating both R and Python versions.

**Comment by rargelaguet** [comment] 2019-01-17 13:56
Could you reinstall both the R package and python package and try again? Apologies for the inconvenience :)

**Comment by brickyyyy** [comment] 2019-01-17 14:09
Still the same output, unfortunately, I can see someone else has reported the same behavior as well.

**Comment by rargelaguet** [comment] 2019-01-17 15:21
Yes but it should be fixed in the last version.. I can't reproduce the error in a fresh new environment

**Closed** 2019-01-19 15:42 UTC
